### ISSUE TITLE
Change the UI of Exercise Tracker 

### ISSUE THREAD

**Issue by azax25547** [azax25547/FCC-API-Microservice#2]
The exercise Tracker's code is in fcc4.js

1. There should be a datepicker, user should not write a date
2. The time input view should be changed. A user should enter hours and minutes so that he/she can input the details instead of inputting minutes only. Later the total minute time will be send to backend as it was.

**Comment by PPInfy** [comment]
Picking this up

**Comment by azax25547** [comment]
> Picking this up

Sure 🤗🤗
